services:

  ui:
    # TODO: add service discovery config
    image: "powertac/ui:${UI_VERSION}"
    ports:
      - "127.0.0.1:${UI_HOST_PORT}:9000"

  orchestrator:
    depends_on:
      mysql:
        condition: service_healthy
    image: "powertac/orchestrator:${ORCHESTRATOR_VERSION}"
    volumes:
      - "./dev.properties:/opt/powertac/orchestrator/application.properties"
      - "${EXPERIMENT_SCHEDULER_ROOT}:/var/opt/powertac"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "127.0.0.1:${ORCHESTRATOR_HOST_PORT}:8080"
    environment:
      EXPERIMENT_SCHEDULER_ROOT: "${EXPERIMENT_SCHEDULER_ROOT}"
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  mysql:
    image: "mariadb:${MARIADB_VERSION}"
    volumes:
      - "${MYSQL_STORAGE_PATH}:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: powertac_experiment_scheduler
      MYSQL_USER: powertac_experiment_scheduler
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    healthcheck:
      test: "/usr/bin/mysql -uroot -p${MYSQL_PASSWORD} --execute \"USE powertac_experiment_scheduler;\""
      start_period: 1m30s
      interval: 30s
      timeout: 1s
      retries: 5